version: "2.2"

services:
  web-app-service:
    build:
      context: WebApplication/
      dockerfile: Dockerfile
    ports:
      - 8080:8080
  email-service:
    build:
      context: EmailService/
      dockerfile: Dockerfile
    ports:
      - 8081:8081
  log4shell-service:
    build:
      context: Log4ShellServer/
      dockerfile: Dockerfile
    ports:
      - 8082:8082
      - 1389:1389
  mysql:
    image: mysql:8.0
    ports:
      - "3306:3306"
    environment:
      - MYSQL_ROOT_PASSWORD=
      - MYSQL_ALLOW_EMPTY_PASSWORD=true
      - MYSQL_USER=petclinic
      - MYSQL_PASSWORD=petclinic
      - MYSQL_DATABASE=petclinic
    volumes:
      - "./conf.d:/etc/mysql/conf.d:ro"
    profiles:
    - mysql
  postgres:
    image: postgres:15.3
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=petclinic
      - POSTGRES_USER=petclinic
      - POSTGRES_DB=petclinic
    profiles:
    - postgres
