events {
  
}

http {
  
  server {
    server_name  dev.petclinic;
    listen 10000;

    location / {
      proxy_pass http://petclinic-app-assess:8080/;
    }
  }

  server {
    server_name  qa.petclinic;
    listen 10000;

    location / {
      proxy_pass http://petclinic-app-qa:8080/;
    }
  }

  server {
    server_name  prod.petclinic;
    listen 10000;

    location / {
      proxy_pass http://petclinic-app-protect:8080/;
    }
  }

}

